import "./globals.css";
import Navbar from "./components/Navbar";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans w-[100%]">
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
